### ISSUE TITLE
Breaking ArchiSteamFarm

### ISSUE THREAD

**Issue by GonzalezAtWork** [Rudokhvist/BoosterCreator#22]
Using ASF 5.5.1.4 on win 64, have this error:

![image](https://github.com/Rudokhvist/BoosterCreator/assets/6012415/408a0848-6b94-499f-8410-3aae8d41f4aa)

and then, it quits the ASF.

How to fix it, or a new version is needed?

FYI: this was also happening on older ASF versions

**Comment by Rudokhvist** [comment]
This plugin only works with ASF-generic, it's stated on the main repository page in big letters. You are trying to use it with ASF-win64 instead, that's what causes the crash. Either switch to ASF-generic or don't use this plugin.
